---
title: "Estacionalidad compleja"
date: "04/10/23"
output: html_notebook
---


```{r}
library(tidyverse)
library(tsibble)
library(fable)
library(feasts)
library(fpp3)
library(patchwork)
```

#Demanda de energia en Victoria, Australia

```{r}
vic_elec
```

```{r}
p <- vic_elec %>%
  autoplot(Demand)

plotly::ggplotly(p)
```

```{r}
s_y <- vic_elec %>% 
  gg_season(Demand, period = "year")
s_w <- vic_elec %>% 
  gg_season(Demand, period = "week")
s_d <- vic_elec %>% 
  gg_season(Demand, period = "day")

s_y/s_w/s_d

```

```{r}
# | fig-height: 10

comp_stl <- vic_elec %>% 
  model(
    STL(Demand, robust = TRUE)
  ) %>% 
  components() 

comp_stl %>% 
  autoplot()

```

```{r}
comp_stl %>% 
  autoplot(season_year)
comp_stl %>% 
  autoplot(season_week)
comp_stl %>% 
  autoplot(season_day)
comp_stl %>% 
  ggplot(aes(x = Time, y = season_adjust)) +
  geom_line()

```

```{r}
vic_train <- vic_elec %>% 
  filter_index(. ~ "2014-09-30")

fit1 <- vic_train %>% 
  model(ets = ETS(Demand ~ error("A") + trend("Ad") + season("A")))

report(fit1)

```

```{r}
p <- vic_train %>% 
  autoplot(Demand) +
  geom_line(aes(y = .fitted), data = fit1 %>% augment(), color = "firebrick")

plotly::ggplotly(p)

```

```{r}
accuracy(fit1)
```

```{r}
fit2 <- vic_train %>% 
  model(
    dcmp = decomposition_model(
      STL(Demand, robust = TRUE),
      ETS(season_adjust ~ error("A") + trend("Ad") + season("N"))
    )
  )

fit2 %>%report()

```

```{r}
fit3 <- vic_train %>% 
  model(
    harmonic = ARIMA(Demand ~ fourier(period = "year", K = 5) +
                       fourier(period = "week", K = 3) +
                       fourier(period = "day", K = 3) + PDQ(0,0,0) + pdq(2,0,2))
  )

report(fit3)

```

```{r}
fc3 <- fit3 %>% 
  forecast(h = "3 months")

fc3 %>% 
  autoplot(vic_elec %>% filter_index("2014-10-01"~.), level = NULL)

fc3 %>% 
  autoplot(vic_elec %>% filter_index("2014-10-01"~.))

fc3 %>% 
  accuracy(vic_elec)

```

```{r}
elec <- vic_elec |>
  mutate(
    DOW = wday(Date, label = TRUE),
    Working_Day = !Holiday & !(DOW %in% c("Sat", "Sun")),
    Cooling = pmax(Temperature, 18)
  )
elec |>
  ggplot(aes(x=Temperature, y=Demand, col=Working_Day)) +
  geom_point(alpha = 0.6) +
  labs(x="Temperature (degrees Celsius)", y="Demand (MWh)")

```


```{r}
library(tidyquant)

data = tq_get("^GSPC", get="stock.prices", from = "2022-01-01", to = "2024-03-28") %>% select(date, adjusted) %>% as_tsibble(index=date)

```


```{r}
data
```

```{r}
data = tq_get("^GSPC", get="stock.prices", from = "2022-01-01", to = "2024-03-28") %>% select(date, adjusted) %>% as_tsibble(index=date)
```


```{r}
calls <- data |>
  mutate(t = row_number()) |>
  update_tsibble(index = t, regular = TRUE) %>% select(t, adjusted)
calls |>
  model(
    STL(adjusted ~ season(period = 5) + season(period = 20) + season(period = 252),
        robust = TRUE)
  ) |>
  components() |>
  autoplot() + labs(x = "Observation")

```

```{r}
calls <- data |>
  
```

```{r}
my_dcmp_spec <- decomposition_model(
  STL(adjusted ~ season(period = 5) + season(period = 20) + season(period = 252),
      robust = TRUE),
  ETS(season_adjust ~ season("N"))
)
fc <- calls |>
  model(my_dcmp_spec) |>
  forecast(h=25)
```


```{r}
plot = fc |>
  fill_gaps() |>
  autoplot(calls) +
  labs(y = "SP500",
       title = "SP500")

plot
```

```{r}
fit3 <- calls %>% 
  model(
    harmonic = ARIMA(adjusted ~ trend() + fourier(period = 5, K = 2) + fourier(period = 25, K = 4) + fourier(period = 252, K=10))
)
```


```{r}
fc <- fit3 %>%
  forecast(h = 25)

fc%>%
  fill_gaps() %>%
  autoplot(calls) +
  labs(y = "SP500", 
       title = "SP500")
  
```
La diferencia entre un modelo y otro es que este modelo está mucho más ajustado y que las acciones se puede ver mucha mejor tendencia en el segundo modelo mientras en el primero a pesar de ser más exacto tiene mucho más ruido y creo que no es tan exacto

```{r}
data_fill_na = fill_gaps(data) %>% fill(adjusted, .direction = "down")
data_fill_na
 comp_stl <- data_fill_na %>% 
  model(
    STL(adjusted, robust = TRUE)
  ) %>% 
  components() 

comp_stl %>% 
  autoplot()

```

```{r}
comp_stl %>% 
  autoplot(season_year)
comp_stl %>% 
  autoplot(season_week)
comp_stl %>% 
  ggplot(aes(x = date, y = season_adjust)) +
  geom_line()
```

```{r}
my_dcmp_spec <- decomposition_model(
  STL(adjusted ~ season(period = 5),
      robust = TRUE),
  ETS(season_adjust)
)
fc <- data_fill_na |>
  model(my_dcmp_spec) |>
  forecast(h = 20)
```


```{r}
plot = fc |>
  fill_gaps() |>
  autoplot(data_fill_na) +
  labs(y = "SP500",
       title = "SP500")

plot
```

```{r}
fit3 <- data_fill_na %>% 
  model(
    harmonic = ARIMA(adjusted ~ trend() + fourier(period = 5, K = 2) + fourier(period = 252, K = 20))
  )
```


```{r}
fit3 <- data_fill_na %>% 
  model(
    harmonic = ARIMA(adjusted ~ fourier(period = "week", K = 2) +
          fourier(period = "year", K = 3))
  )
```

```{r}
library(fable.prophet)
colnames(data) = c("ds", "y")
fit_prophet = data%>%model(prophet =prophet(y))
```


```{r}
fc<-fit_prophet%>% forecast(h=25)
fc%>% autoplot(data)
```

```{r}
fit_prophet |>
  components() |>
  autoplot()

components(fit_prophet)

fit_prophet = data %>% model(prophet(y ~ season(type = "additive")))



fc <- fit_prophet %>% forecast(h = 25)
fc %>% autoplot(data)
```



